name: time-stuff
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py312h06a4308_0
  - aiohttp=3.11.10=py312h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=19.0.0=h865e1df_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=24.3.0=py312h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.11.212=hecad206_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2025.1.31=py312h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - datasets=2.19.1=py312h06a4308_0
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - dill=0.3.8=py312h06a4308_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h6a678d5_0
  - filelock=3.13.1=py312h06a4308_0
  - frozenlist=1.5.0=py312h5eee18b_0
  - fsspec=2024.3.1=py312h06a4308_0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcurl=8.11.1=hc9e6f67_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libuuid=1.41.5=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - multidict=6.1.0=py312h5eee18b_0
  - multiprocess=0.70.15=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.10.1=py312h3c60e43_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - openssl=3.0.15=h5eee18b_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.2=py312h06a4308_0
  - pandas=2.2.3=py312h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py312h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - propcache=0.2.0=py312h5eee18b_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=19.0.0=py312h6a678d5_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.8=h5148396_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py312h5eee18b_0
  - pytz=2024.1=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py312h5eee18b_0
  - requests=2.32.3=py312h06a4308_1
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.5=py312hc50d6dc_1
  - setuptools=75.8.0=py312h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py312h5eee18b_0
  - tqdm=4.66.5=py312he106c6f_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py312h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py312h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py312h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.3.0
      - adjusttext==1.3.0
      - annotated-types==0.7.0
      - backcall==0.2.0
      - beartype==0.14.1
      - beautifulsoup4==4.13.4
      - better-abc==0.0.3
      - bitsandbytes==0.46.1
      - bleach==6.2.0
      - blis==1.2.0
      - bs4==0.0.2
      - catalogue==2.0.10
      - chatintents==0.0.1
      - choreographer==1.0.9
      - click==8.1.8
      - cloudpathlib==0.20.0
      - cloudpickle==3.1.1
      - confection==0.1.5
      - contourpy==1.3.1
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==3.1.0
      - data==0.4
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - docopt==0.6.2
      - einops==0.8.1
      - en-core-web-lg==3.8.0
      - en-core-web-sm==3.8.0
      - evaluate==0.4.3
      - fancy-einsum==0.0.3
      - fastjsonschema==2.21.1
      - fonttools==4.56.0
      - funcsigs==1.0.2
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hdbscan==0.8.40
      - hopcroftkarp==1.2.5
      - huggingface-hub==0.31.2
      - hyperopt==0.2.7
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - jaxtyping==0.3.2
      - jinja2==3.1.5
      - joblib==1.4.2
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.15
      - kaleido==1.0.0
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - logistro==1.1.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - murmurhash==1.0.12
      - narwhals==1.47.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - nptyping==2.5.0
      - numba==0.61.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - orjson==3.11.0
      - pandocfilters==1.5.1
      - persim==0.3.8
      - pfzy==0.3.4
      - pillow==11.1.0
      - pip-chill==1.0.3
      - pipreqs==0.5.0
      - plotly==6.2.0
      - preshed==3.0.9
      - protobuf==3.20.1
      - psutil==6.1.1
      - py4j==0.10.9.9
      - pycolormap-2d==1.0.10
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pynndescent==0.5.13
      - pyparsing==3.2.1
      - pyppur==0.1.0
      - referencing==0.36.2
      - rich==13.9.4
      - ripser==0.6.12
      - rpds-py==0.25.1
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - shutilwhich==1.1.0
      - simplejson==3.20.1
      - sklearn-som==1.1.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - soupsieve==2.7
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.13.1
      - tempdir==0.7.1
      - thinc==8.3.4
      - threadpoolctl==3.5.0
      - tifffile==2025.6.11
      - timexy==0.1.3
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - transformer-lens==2.16.0
      - transformers==4.51.3
      - transformers-stream-generator==0.0.5
      - triton==3.2.0
      - typeguard==4.4.3
      - typer==0.15.1
      - typing-extensions==4.14.0
      - umap-learn==0.5.7
      - wadler-lindig==0.1.6
      - wandb==0.20.1
      - wasabi==1.1.3
      - weasel==0.4.1
      - webencodings==0.5.1
      - widgetsnbextension==4.0.14
      - wikipedia==1.4.0
      - wrapt==1.17.2
      - yarg==0.1.9
