global:
  delta_token: 0
  debug: false
  frac: 1
  use_quantization: true

grid:
  model_name:
    - '/storage/ukp/shared/shared_model_weights/models--llama-3.1/hf/70B-Instruct'
    - '/storage/ukp/shared/shared_model_weights/models--llama-3.1/hf/8B-Instruct'

local:
  - datasets:
    - filename: datasets/templates/date_3way_season.csv
      label_columns: [correct_season, correct_season_label, correct_date]
      extra_columns: [correct_date_str]

    - filename: datasets/templates/time_of_day_3way.csv
      label_columns: [correct_time, correct_answer, correct_time_diff]
      extra_columns: [correct_time_expr]

    - filename: datasets/templates/time_of_day_3way_phase.csv
      label_columns: [correct_time, correct_answer, correct_phase, correct_phase_label]
      extra_columns: [correct_time_expr]

    - filename: datasets/templates/duration_3way.csv
      label_columns: [correct_duration_length, correct_date, correct_end_date, correct_month]
      extra_columns: [correct_duration_str, correct_date_expr]

    - filename: datasets/templates/date_3way.csv
      label_columns: [correct_date]
      extra_columns: [correct_date_str]

    - filename: datasets/templates/date_3way_temperature.csv
      label_columns: [correct_temperature, correct_temperature_label, correct_date]

    - filename: datasets/templates/periodic_3way.csv
      label_columns: [correct_period_length, period_type]
      extra_columns: [correct_period_str]

    - filename: datasets/templates/notable_3way.csv
      label_columns: [correct_date]
