global:
  delta_token: 0
  debug: false
  frac: 1
  model_name: meta-llama/Llama-3.2-3B-Instruct
  intervention_layer: 1

grid:
  noise_scale:
    - 0
    - 0.5
    - 1
    - 5
    - 10
    - 50
  n_components:
    - 2
    - 5
    - 10
    - 50
    - 100
    - 500
  intervention_type:
    - full
    - rand
    - replace

local:
  - dataset: datasets/templates/time_of_day_3way_phase.csv
    label_column: correct_phase_label
    target_column: correct_time_expr
    manifold: cluster

  - dataset: datasets/templates/date_3way.csv
    label_column: correct_date
    target_column: correct_date_str
    preprocess_func: datetime_to_dayofyear
    manifold: circular

  - dataset: datasets/templates/date_3way_season.csv
    label_column: correct_season_label
    target_column: correct_date_str
    manifold: cluster


