global:
  reduction_method: SMDS
  k: 5
  target_columns: null
  layers: null
  max_samples: 500

grid:
  n_components: [2, 3, 4]
  manifold: 
    - euclidean
    - discrete_circular
    - cluster
    - circular
    - semicircular
    - log_linear
    - log_semicircular

local:

  #### llama-3.2-3b-instruct ####
  - path: results/Llama-3.2-3B-Instruct/duration_3way.pt
    label_col: [correct_duration_length, correct_date]
    preprocess_func: [log, datetime_to_dayofyear]

  - path: results/Llama-3.2-3B-Instruct/duration_3way.pt
    label_col: correct_duration_length

  - path: results/Llama-3.2-3B-Instruct/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/Llama-3.2-3B-Instruct/date_3way_season.pt
    label_col: correct_season_label

  - path: results/Llama-3.2-3B-Instruct/date_3way_temperature.pt
    label_col: correct_temperature_label

  - path: results/Llama-3.2-3B-Instruct/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/Llama-3.2-3B-Instruct/time_of_day_3way_phase.pt
    label_col: correct_phase_label

  - path: results/Llama-3.2-3B-Instruct/periodic_3way.pt
    label_col: correct_period_length

  - path: results/Llama-3.2-3B-Instruct/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023

  #### Llama-3.1-8B-Instruct ####
  - path: results/8B-Instruct/duration_3way.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: [correct_duration_length, correct_date]
    preprocess_func: [log, datetime_to_dayofyear]

  - path: results/8B-Instruct/duration_3way.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_duration_length

  - path: results/8B-Instruct/date_3way.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/8B-Instruct/date_3way_season.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_season_label

  - path: results/8B-Instruct/date_3way_temperature.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_temperature_label

  - path: results/8B-Instruct/time_of_day_3way.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/8B-Instruct/time_of_day_3way_phase.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_phase_label

  - path: results/8B-Instruct/periodic_3way.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_period_length

  - path: results/8B-Instruct/notable_3way.pt
    model_name: meta-llama/Llama-3.1-8B-Instruct
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023

  #### Llama-3.1-70B-Instruct ####
  - path: results/70B-Instruct/duration_3way.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: [correct_duration_length, correct_date]
    preprocess_func: [log, datetime_to_dayofyear]

  - path: results/70B-Instruct/duration_3way.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_duration_length

  - path: results/70B-Instruct/date_3way.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear

  - path: results/70B-Instruct/date_3way_season.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_season_label

  - path: results/70B-Instruct/date_3way_temperature.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_temperature_label

  - path: results/70B-Instruct/time_of_day_3way.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_time
    preprocess_func: datetime_to_hour

  - path: results/70B-Instruct/time_of_day_3way_phase.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_phase_label

  - path: results/70B-Instruct/periodic_3way.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_period_length

  - path: results/70B-Instruct/notable_3way.pt
    model_name: meta-llama/Llama-3.1-70B-Instruct
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023
