global:
  reduction_method: SMDS
  k: 5
  target_columns: null
  layers: null
  max_samples: 500

grid:
  n_components: [3]

local:
### Non Control Configurations ###
  #### gemma-2-2b-it ####
  - path: results/gemma-2-2b-it/duration_3way.pt
    label_col: correct_duration_length
    manifold: log_linear

  - path: results/gemma-2-2b-it/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear
    manifold: circular

  - path: results/gemma-2-2b-it/date_3way_season.pt
    label_col: correct_season_label
    manifold: cluster

  - path: results/gemma-2-2b-it/date_3way_temperature.pt
    label_col: correct_temperature_label
    manifold: cluster

  - path: results/gemma-2-2b-it/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour
    manifold: semicircular

  - path: results/gemma-2-2b-it/time_of_day_3way_phase.pt
    label_col: correct_phase_label
    manifold: cluster

  - path: results/gemma-2-2b-it/periodic_3way.pt
    label_col: correct_period_length
    manifold: log_linear

  - path: results/gemma-2-2b-it/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023
    manifold: semicircular

  #### llama-3.2-3b-instruct ####
  - path: results/Llama-3.2-3B-Instruct/duration_3way.pt
    label_col: correct_duration_length
    manifold: log_linear

  - path: results/Llama-3.2-3B-Instruct/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear
    manifold: circular

  - path: results/Llama-3.2-3B-Instruct/date_3way_season.pt
    label_col: correct_season_label
    manifold: cluster

  - path: results/Llama-3.2-3B-Instruct/date_3way_temperature.pt
    label_col: correct_temperature_label
    manifold: cluster

  - path: results/Llama-3.2-3B-Instruct/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour
    manifold: circular

  - path: results/Llama-3.2-3B-Instruct/time_of_day_3way_phase.pt
    label_col: correct_phase_label
    manifold: cluster

  - path: results/Llama-3.2-3B-Instruct/periodic_3way.pt
    label_col: correct_period_length
    manifold: log_linear

  - path: results/Llama-3.2-3B-Instruct/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023
    manifold: semicircular

  #### Qwen2.5-3B-Instruct ####
  - path: results/Qwen2.5-3B-Instruct/duration_3way.pt
    label_col: correct_duration_length
    manifold: log_linear

  - path: results/Qwen2.5-3B-Instruct/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear
    manifold: circular

  - path: results/Qwen2.5-3B-Instruct/date_3way_season.pt
    label_col: correct_season_label
    manifold: cluster

  - path: results/Qwen2.5-3B-Instruct/date_3way_temperature.pt
    label_col: correct_temperature_label
    manifold: cluster

  - path: results/Qwen2.5-3B-Instruct/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour
    manifold: circular

  - path: results/Qwen2.5-3B-Instruct/time_of_day_3way_phase.pt
    label_col: correct_phase_label
    manifold: cluster

  - path: results/Qwen2.5-3B-Instruct/periodic_3way.pt
    label_col: correct_period_length
    manifold: log_linear

  - path: results/Qwen2.5-3B-Instruct/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023
    manifold: semicircular

### Control Configurations ###
  #### gemma-2-2b-it ####
  - path: results/gemma-2-2b-it/duration_3way.pt
    label_col: correct_duration_length
    manifold: log_linear
    control: true

  - path: results/gemma-2-2b-it/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear
    manifold: circular
    control: true

  - path: results/gemma-2-2b-it/date_3way_season.pt
    label_col: correct_season_label
    manifold: cluster
    control: true

  - path: results/gemma-2-2b-it/date_3way_temperature.pt
    label_col: correct_temperature_label
    manifold: cluster
    control: true

  - path: results/gemma-2-2b-it/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour
    manifold: semicircular
    control: true

  - path: results/gemma-2-2b-it/time_of_day_3way_phase.pt
    label_col: correct_phase_label
    manifold: cluster
    control: true

  - path: results/gemma-2-2b-it/periodic_3way.pt
    label_col: correct_period_length
    manifold: log_linear
    control: true

  - path: results/gemma-2-2b-it/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023
    manifold: semicircular
    control: true

  #### llama-3.2-3b-instruct ####
  - path: results/Llama-3.2-3B-Instruct/duration_3way.pt
    label_col: correct_duration_length
    manifold: log_linear
    control: true

  - path: results/Llama-3.2-3B-Instruct/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear
    manifold: circular
    control: true

  - path: results/Llama-3.2-3B-Instruct/date_3way_season.pt
    label_col: correct_season_label
    manifold: cluster
    control: true

  - path: results/Llama-3.2-3B-Instruct/date_3way_temperature.pt
    label_col: correct_temperature_label
    manifold: cluster
    control: true

  - path: results/Llama-3.2-3B-Instruct/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour
    manifold: circular
    control: true

  - path: results/Llama-3.2-3B-Instruct/time_of_day_3way_phase.pt
    label_col: correct_phase_label
    manifold: cluster
    control: true

  - path: results/Llama-3.2-3B-Instruct/periodic_3way.pt
    label_col: correct_period_length
    manifold: log_linear
    control: true

  - path: results/Llama-3.2-3B-Instruct/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023
    manifold: semicircular
    control: true

  #### Qwen2.5-3B-Instruct ####
  - path: results/Qwen2.5-3B-Instruct/duration_3way.pt
    label_col: correct_duration_length
    manifold: log_linear
    control: true

  - path: results/Qwen2.5-3B-Instruct/date_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_dayofyear
    manifold: circular
    control: true

  - path: results/Qwen2.5-3B-Instruct/date_3way_season.pt
    label_col: correct_season_label
    manifold: cluster
    control: true

  - path: results/Qwen2.5-3B-Instruct/date_3way_temperature.pt
    label_col: correct_temperature_label
    manifold: cluster
    control: true

  - path: results/Qwen2.5-3B-Instruct/time_of_day_3way.pt
    label_col: correct_time
    preprocess_func: datetime_to_hour
    manifold: circular
    control: true

  - path: results/Qwen2.5-3B-Instruct/time_of_day_3way_phase.pt
    label_col: correct_phase_label
    manifold: cluster
    control: true

  - path: results/Qwen2.5-3B-Instruct/periodic_3way.pt
    label_col: correct_period_length
    manifold: log_linear
    control: true

  - path: results/Qwen2.5-3B-Instruct/notable_3way.pt
    label_col: correct_date
    preprocess_func: datetime_to_year
    label_shift: -2023
    manifold: semicircular
    control: true