### Example configuration for a generic experiment ###

global: # Settings shared across all experiments
  delta_token: 0
  debug: false
  frac: 1
  use_quantization: false

grid: # Every combination of the parameters in each list will be run
  model_name:
    - gpt2
    - meta-llama/Llama-3.2-3B-Instruct
  manifold: 
    - euclidean
    - cluster
    - circular

local: # Specific settings overriding grid and global
  - datasets:
    - filename: datasets/templates/date_3way.csv
      label_columns: [correct_date]
      extra_columns: [correct_date_str]

    - filename: datasets/templates/notable_3way.csv
      label_columns: [correct_date]
